name: Waka Readme

on:
  # Manual workflow trigger
  workflow_dispatch:
  # Scheduled trigger at 12 AM UTC
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # Ensures the repository is checked out
      - uses: athul/waka-readme@master # This action updates the README with WakaTime stats
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
